### ISSUE TITLE
Kingston Nvme Ssd not showing.

### ISSUE THREAD

**Issue by sloke123** [hexagon-oss/openhardwaremonitor#9]
I'm using a Kingston A2000 500Gb NVME SSD. Unfortunately, It doesn't show anything.
![Hwmonitor](https://user-images.githubusercontent.com/31745181/123500145-8b27b200-d659-11eb-951d-b229772ecdda.jpg)

Original App used to show as a generic hard drive with no temp.

**Comment by pgrawehr** [comment]
That's weird. The drives shown have quite odd values, as if they where brand new. Do these two drives actually exist or are they wrong? 

Try exiting OHM, deleting the file `openhardwaremonitor.config` and then restarting. Does that change anything?

**Comment by sloke123** [comment]
Did as you told but the issue is still present.
![Hwmonitor2](https://user-images.githubusercontent.com/31745181/123525258-eeaeef80-d6ec-11eb-8246-d3625921aef6.jpg)

**Comment by pgrawehr** [comment]
I found a possible cause. I'll probably have a version to test for you tomorrow or so.

**Comment by sloke123** [comment]
Thank You very much.:)

**Comment by pgrawehr** [comment]
Here's a test build that should eventually resolve your issue. One problem I found was that if a device identified as NVMe, but then did not support some of the expected function calls, it was completely ignored. 

Please test whether this build correctly recognizes your disk. There's a log file written to your temp folder (it starts with "OHM"). Can you post the contents of that file, please?

[OHM-0.97-alpha04.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/6731584/OHM-0.97-alpha04.zip)

**Comment by sloke123** [comment]
First of all, I'm very much sorry for the late response. The work pressure was intense. Anyway, This version can detect my nvme but not showing the temp.
![Hwmonitor3](https://user-images.githubusercontent.com/31745181/123843746-dc70c380-d92f-11eb-9c17-667e46a98f3d.jpg)

Here is the log file.
[OHM_2021-06-29.log](https://github.com/hexagon-oss/openhardwaremonitor/files/6735356/OHM_2021-06-29.log)

**Comment by pgrawehr** [comment]
Ok, then it's really the same issue that I have on my laptop. These devices identify as NVMe, but fail to support some of the features that are expected for an NVMe device. I need to find out whether reading the temperature works. For now, it's at least showing the drive again.

**Comment by sloke123** [comment]
I don't know if it will help you in your troubleshooting. I tried another software(HWiFO64) and it looks fine. Here is the screenshot.
![HWiNFO64](https://user-images.githubusercontent.com/31745181/123933386-f651eb00-d9af-11eb-8359-7eed0611f8b0.jpg)

and the log file. I found it in the temp folder.
[HWiNFOMonitor.log](https://github.com/hexagon-oss/openhardwaremonitor/files/6739530/HWiNFOMonitor.log)

**Comment by pgrawehr** [comment]
It seems there was a specification update for NVMe which caused this to break (or rather, it's now broken for older disks). It should be possible to get this fixed, but I need more time for that. I'll post an update if I find time.

**Comment by sloke123** [comment]
Of course, there is no rush. Take your time. And thanks again for helping me out. I really appreciate it.

**Comment by pgrawehr** [comment]
I don't fully understand what I did now (just copied an alternate API call from the Web...) but it appears to work now. Can you test, please?
[OHM-0.97-alpha05.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/6748648/OHM-0.97-alpha05.zip)

**Comment by lordmage** [comment]
> I don't fully understand what I did now (just copied an alternate API call from the Web...) but it appears to work now. Can you test, please?
> [OHM-0.97-alpha05.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/6748648/OHM-0.97-alpha05.zip)

just reporting this version works for my nvme 
![image](https://user-images.githubusercontent.com/46030022/124253570-299e9200-daf6-11eb-88c7-1410da92b491.png)
[OHM_2021-07-02.log](https://github.com/hexagon-oss/openhardwaremonitor/files/6753650/OHM_2021-07-02.log)

**Comment by sloke123** [comment]
> I don't fully understand what I did now (just copied an alternate API call from the Web...) but it appears to work now. Can you test, please?
> [OHM-0.97-alpha05.zip](https://github.com/hexagon-oss/openhardwaremonitor/files/6748648/OHM-0.97-alpha05.zip)

It's working now. Though min value not showing, but its okay. 
![Hwmonitor3](https://user-images.githubusercontent.com/31745181/124343446-246e3f80-dbe9-11eb-889b-b4a850e92840.jpg)

Thank you very much.

**Comment by sloke123** [comment]
Should I close this issue?

**Comment by sloke123** [comment]
Should I close this issue?

**Comment by pgrawehr** [comment]
@sloke123 : Thanks for reporting back. I'll close the issue once the change has been merged to master and I have built a release version.

**Comment by sloke123** [comment]
Thanks, I really appreciate your help. Wish you all the best.

**Comment by cagnulein** [comment]
@pgrawehr  @sloke123  @lordmage the alpha5 doesn't even startup for me...(0.9.7-alpha1 loads correctly). Is there any new dependency that i'm missing?

**Comment by pgrawehr** [comment]
@cagnulein yes, its quite probable that there are new dependencies, however they should be grabbed automatically. I should upload a build, but not sure when I find time.

Meanwhile, you can check the system event log, it typically contains information in such a case.

**Comment by cagnulein** [comment]
hi @pgrawehr thanks for the feedback. You were right, in the event viewer i found this:

<pre>Nome registro: Application
Origine:       .NET Runtime
Data:          02/09/2021 08:09:58
ID evento:     1026
Categoria attività:Nessuna
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      TestRigScadaCE
Descrizione:
Application: OpenHardwareMonitor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateSensors()
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric..ctor(System.String, OpenHardwareMonitor.Hardware.HDD.NVMeInfo, Int32, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateInstance(OpenHardwareMonitor.Hardware.HDD.StorageInfo, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.AbstractStorage.CreateInstance(Int32, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.HarddriveGroup..ctor(OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.Computer.set_HDDEnabled(Boolean)
   at OpenHardwareMonitor.GUI.MainForm.<.ctor>b__38_18(System.Object, System.EventArgs)
   at OpenHardwareMonitor.GUI.UserOption.add_Changed(System.EventHandler)
   at OpenHardwareMonitor.GUI.MainForm..ctor()
   at OpenHardwareMonitor.Program.Main(System.String[])


XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-02T06:09:58.412949200Z" />
    <EventRecordID>25009</EventRecordID>
    <Channel>Application</Channel>
    <Computer>TestRigScadaCE</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: OpenHardwareMonitor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateSensors()
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric..ctor(System.String, OpenHardwareMonitor.Hardware.HDD.NVMeInfo, Int32, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.NVMeGeneric.CreateInstance(OpenHardwareMonitor.Hardware.HDD.StorageInfo, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.AbstractStorage.CreateInstance(Int32, OpenHardwareMonitor.Hardware.HDD.NVMeGeneric, OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.HDD.HarddriveGroup..ctor(OpenHardwareMonitor.Hardware.ISettings)
   at OpenHardwareMonitor.Hardware.Computer.set_HDDEnabled(Boolean)
   at OpenHardwareMonitor.GUI.MainForm.&lt;.ctor&gt;b__38_18(System.Object, System.EventArgs)
   at OpenHardwareMonitor.GUI.UserOption.add_Changed(System.EventHandler)
   at OpenHardwareMonitor.GUI.MainForm..ctor()
   at OpenHardwareMonitor.Program.Main(System.String[])

</Data>
  </EventData>
</Event></pre>

With CrystalDiskInfo i saw the sensors correctly

**Comment by pgrawehr** [comment]
@cagnulein This seems to be a special case or a new issue. Would you mind creating a new issue for this?
